import { useState } from "react";
import { CheckCircle2, FileUp, Loader2 } from "lucide-react";
import { SectionHeader } from "@/components/dashboard/SectionHeader";
import { uploadDataset } from "@/services/api.js";
import { useDecisionSystem } from "@/context/DecisionSystemContext";

export default function DatasetUploadPage() {
  const { setDataset, problemContext, setProblemContext } = useDecisionSystem();
  const [file, setFile] = useState(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  const update = (key, value) => setProblemContext({ ...problemContext, [key]: value });
  const submit = async (e) => { e.preventDefault(); setError(""); setSuccess(""); if (!file) return setError("Please choose a CSV file before submitting."); setLoading(true); try { const result = await uploadDataset({ file, ...problemContext }); setDataset({ name: file.name, experimentId: result.experimentId }); setSuccess(`Dataset accepted. Experiment ${result.experimentId} is ready for profiling.`); } catch (err) { setError(err?.message || "Upload failed"); } finally { setLoading(false); } };
  return <div className="animate-enter-up"><SectionHeader eyebrow="Dataset intake" title="Upload dataset and context" description="Pair CSV data with the decision goal, operational priorities, and constraints before pipeline reasoning begins." />
    <form onSubmit={submit} className="grid gap-6 lg:grid-cols-[1fr_1.1fr]"><label className="panel flex min-h-72 cursor-pointer flex-col items-center justify-center rounded-lg border border-dashed p-8 text-center transition hover:-translate-y-1 hover:border-primary"><FileUp className="h-12 w-12 text-primary" /><span className="mt-4 font-display text-xl font-bold">{file ? file.name : "Drop or select a CSV file"}</span><span className="mt-2 text-sm text-muted-foreground">CSV upload is sent to POST /upload when a backend is configured.</span><input className="sr-only" type="file" accept=".csv,text/csv" onChange={(e) => setFile(e.target.files?.[0] || null)} /></label>
      <section className="panel rounded-lg border p-6"><div className="grid gap-4 sm:grid-cols-2"><label className="space-y-2"><span className="text-sm font-semibold">Problem type</span><select value={problemContext.problemType} onChange={(e) => update("problemType", e.target.value)} className="w-full rounded-md border bg-background px-3 py-2"><option>classification</option><option>regression</option></select></label><label className="space-y-2"><span className="text-sm font-semibold">Priority</span><select value={problemContext.priority} onChange={(e) => update("priority", e.target.value)} className="w-full rounded-md border bg-background px-3 py-2"><option>accuracy</option><option>recall</option><option>explainability</option></select></label><label className="space-y-2 sm:col-span-2"><span className="text-sm font-semibold">Target column</span><input value={problemContext.targetColumn} onChange={(e) => update("targetColumn", e.target.value)} className="w-full rounded-md border bg-background px-3 py-2" placeholder="e.g. readmission_risk" /></label><label className="space-y-2 sm:col-span-2"><span className="text-sm font-semibold">Constraints</span><textarea value={problemContext.constraints} onChange={(e) => update("constraints", e.target.value)} className="min-h-28 w-full rounded-md border bg-background px-3 py-2" placeholder="Latency, fairness, interpretability, compliance..." /></label></div>{error && <p className="mt-4 rounded-md bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}{success && <p className="mt-4 flex items-center gap-2 rounded-md bg-success/10 p-3 text-sm text-success"><CheckCircle2 className="h-4 w-4" />{success}</p>}<button disabled={loading} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-md bg-primary px-4 py-3 font-semibold text-primary-foreground shadow-glow disabled:cursor-not-allowed disabled:opacity-60">{loading && <Loader2 className="h-4 w-4 animate-spin" />}Submit dataset</button></section></form>
  </div>;
}
